#Data preprocessing

###import Libraries

In [ ]:
import pandas as pd
import numpy as np

###Read Dataset

In [ ]:
df=pd.read_csv("/content/Iris_1.csv")
df.head()     #Understand the Datasets

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df.sample(8)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
96,97,5.7,2.9,4.2,1.3,Iris-versicolor
111,112,6.4,2.7,5.3,1.9,Iris-virginica
1,2,4.9,3.0,1.4,0.2,Iris-setosa
117,118,7.7,3.8,6.7,2.2,Iris-virginica
106,107,4.9,2.5,4.5,1.7,Iris-virginica
77,78,6.7,3.0,5.0,1.7,Iris-versicolor
17,18,5.1,3.5,1.4,0.3,Iris-setosa
5,6,5.4,3.9,NaN,NaN,Iris-setosa

###Intial Inspection

In [ ]:
print(df.shape)

(150, 6)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  148 non-null    float64
 2   SepalWidthCm   147 non-null    float64
 3   PetalLengthCm  146 non-null    float64
 4   PetalWidthCm   144 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     148.000000    147.000000     146.000000    144.000000
mean    75.500000       5.858784      3.050340       3.820548      1.235417
std     43.445368       0.822716      0.435949       1.747586      0.756461
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.400000      1.350000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
df1 = df.copy(deep=True)   #Does not change in Orginal DS

##Checking all the Null values

In [ ]:
df1.isna().sum()

Id               0
SepalLengthCm    2
SepalWidthCm     3
PetalLengthCm    4
PetalWidthCm     6
Species          0
dtype: int64

In [ ]:
df1.head(25)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            NaN           NaN  Iris-setosa
6    7            NaN           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           NaN            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            NaN           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            NaN           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           NaN            1.7           0.2  Iris-setosa
21  22            5.1           3.7            NaN           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           NaN  Iris-setosa
24  25            4.8           3.4            1.9           NaN  Iris-setosa

#Filling Null Values

### 1. Mannually Filling Null Values

In [ ]:
df1["SepalLengthCm"].fillna(7.2,inplace=True)
df1.head(15)

/tmp/ipykernel_1014/2623590609.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["SepalLengthCm"].fillna(7.2,inplace=True)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            NaN           NaN  Iris-setosa
6    7            7.2           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           NaN            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            7.2           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            NaN           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa

###2. Filling null Values with its Median

In [ ]:
med = df1["SepalWidthCm"].median()
df1["SepalWidthCm"]=df1["SepalWidthCm"].fillna(med)
df1.head(15)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            NaN           NaN  Iris-setosa
6    7            7.2           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           3.0            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            7.2           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            NaN           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa

###3.Fill Null Values with Mean

In [ ]:
me=df1["PetalLengthCm"].mean()
df1["PetalLengthCm"]=df1["PetalLengthCm"].fillna(me)
df1.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5       1.400000           0.2  Iris-setosa
1   2            4.9           3.0       1.400000           0.2  Iris-setosa
2   3            4.7           3.2       1.300000           0.2  Iris-setosa
3   4            4.6           3.1       1.500000           0.2  Iris-setosa
4   5            5.0           3.6       1.400000           0.2  Iris-setosa
5   6            5.4           3.9       3.820548           NaN  Iris-setosa
6   7            7.2           3.4       1.400000           0.3  Iris-setosa
7   8            5.0           3.4       1.500000           0.2  Iris-setosa
8   9            4.4           3.0       1.400000           0.2  Iris-setosa
9  10            4.9           3.1       1.500000           0.1  Iris-setosa

In [ ]:
df1.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     6
Species          0
dtype: int64

In [ ]:
df1=df1.dropna()
df1.head(10)
#df1 = df1.dropna(subset=["PetalWidthCm	"],axis=0)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
6    7            7.2           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           3.0            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa

In [ ]:
df1.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
print(df1.shape)

(144, 6)

##Adaitional Filling Methods
###1. df1["coloumn_name"].fillna(method="bdill")
###2. df1["coloumn_name"].fillna(method="ffill")