In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df= pd.read_csv("/content/Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.shape

(150, 6)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
df.isna().sum()  #STEP 1: Eleminate the Null values

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

###STEP 2 : In Data Preprocessing , Convert Categorical Col to Numerical column

In [ ]:
#To Find Values In Column
df["Species"].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

###1. Manual Conersion

In [ ]:
df1=df.copy(deep=True)
mapping={"Iris-setosa":3, "Iris-versicolor":2 ,"Iris-virginica":1}
df1["Species"]=df1["Species"].map(mapping)
df1.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        3
1   2            4.9           3.0            1.4           0.2        3
2   3            4.7           3.2            1.3           0.2        3
3   4            4.6           3.1            1.5           0.2        3
4   5            5.0           3.6            1.4           0.2        3

In [ ]:
df1.tail()

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
145  146            6.7           3.0            5.2           2.3        1
146  147            6.3           2.5            5.0           1.9        1
147  148            6.5           3.0            5.2           2.0        1
148  149            6.2           3.4            5.4           2.3        1
149  150            5.9           3.0            5.1           1.8        1

###1. label Encoder

In [ ]:
#It is convert each value in a column to number
df2=df.copy(deep=True)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df2["Species"]=le.fit_transform(df2["Species"])
df2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [ ]:
df2["Species"]=le.inverse_transform(df2["Species"])
df2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

###2. One Hot Encoding

In [ ]:
df3=df.copy(deep=True)
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
x3=df3[["Species"]]    #[] use for multiple columns
ohe.fit_transform(x3).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

###4. Dummy Variables

In [ ]:
# This is Same as OneCodeEncoding But it comes with column names
pd.get_dummies(df3["Species"])

     Iris-setosa  Iris-versicolor  Iris-virginica
0           True            False           False
1           True            False           False
2           True            False           False
3           True            False           False
4           True            False           False
..           ...              ...             ...
145        False            False            True
146        False            False            True
147        False            False            True
148        False            False            True
149        False            False            True

[150 rows x 3 columns]

##Feature Scaling
##1. Min Max Scaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler
df4=df.copy(deep=True)
x2=df4.iloc[:,0:5]  #iloc=integer location  # row,column
mms=MinMaxScaler(feature_range=(1,2))  # x_Scaled = (x-x_min)/(x_max-x_min)
x2_Scaled=mms.fit_transform(x2)
x2_Scaled

array([[1.        , 1.22222222, 1.625     , 1.06779661, 1.04166667],
       [1.00671141, 1.16666667, 1.41666667, 1.06779661, 1.04166667],
       [1.01342282, 1.11111111, 1.5       , 1.05084746, 1.04166667],
       [1.02013423, 1.08333333, 1.45833333, 1.08474576, 1.04166667],
       [1.02684564, 1.19444444, 1.66666667, 1.06779661, 1.04166667],
       [1.03355705, 1.30555556, 1.79166667, 1.11864407, 1.125     ],
       [1.04026846, 1.08333333, 1.58333333, 1.06779661, 1.08333333],
       [1.04697987, 1.19444444, 1.58333333, 1.08474576, 1.04166667],
       [1.05369128, 1.02777778, 1.375     , 1.06779661, 1.04166667],
       [1.06040268, 1.16666667, 1.45833333, 1.08474576, 1.        ],
       [1.06711409, 1.30555556, 1.70833333, 1.08474576, 1.04166667],
       [1.0738255 , 1.13888889, 1.58333333, 1.10169492, 1.04166667],
       [1.08053691, 1.13888889, 1.41666667, 1.06779661, 1.        ],
       [1.08724832, 1.        , 1.41666667, 1.01694915, 1.        ],
       [1.09395973, 1.41666667, 1.83333333, 1.03389831, 1.04166667],
       [1.10067114, 1.38888889, 2.        , 1.08474576, 1.125     ],
       [1.10738255, 1.30555556, 1.79166667, 1.05084746, 1.125     ],
       [1.11409396, 1.22222222, 1.625     , 1.06779661, 1.08333333],
       [1.12080537, 1.38888889, 1.75      , 1.11864407, 1.08333333],
       [1.12751678, 1.22222222, 1.75      , 1.08474576, 1.08333333],
       [1.13422819, 1.30555556, 1.58333333, 1.11864407, 1.04166667],
       [1.1409396 , 1.22222222, 1.70833333, 1.08474576, 1.125     ],
       [1.14765101, 1.08333333, 1.66666667, 1.        , 1.04166667],
       [1.15436242, 1.22222222, 1.54166667, 1.11864407, 1.16666667],
       [1.16107383, 1.13888889, 1.58333333, 1.15254237, 1.04166667],
       [1.16778523, 1.19444444, 1.41666667, 1.10169492, 1.04166667],
       [1.17449664, 1.19444444, 1.58333333, 1.10169492, 1.125     ],
       [1.18120805, 1.25      , 1.625     , 1.08474576, 1.04166667],
       [1.18791946, 1.25      , 1.58333333, 1.06779661, 1.04166667],
       [1.19463087, 1.11111111, 1.5       , 1.10169492, 1.04166667],
       [1.20134228, 1.13888889, 1.45833333, 1.10169492, 1.04166667],
       [1.20805369, 1.30555556, 1.58333333, 1.08474576, 1.125     ],
       [1.2147651 , 1.25      , 1.875     , 1.08474576, 1.        ],
       [1.22147651, 1.33333333, 1.91666667, 1.06779661, 1.04166667],
       [1.22818792, 1.16666667, 1.45833333, 1.08474576, 1.        ],
       [1.23489933, 1.19444444, 1.5       , 1.03389831, 1.04166667],
       [1.24161074, 1.33333333, 1.625     , 1.05084746, 1.04166667],
       [1.24832215, 1.16666667, 1.45833333, 1.08474576, 1.        ],
       [1.25503356, 1.02777778, 1.41666667, 1.05084746, 1.04166667],
       [1.26174497, 1.22222222, 1.58333333, 1.08474576, 1.04166667],
       [1.26845638, 1.19444444, 1.625     , 1.05084746, 1.08333333],
       [1.27516779, 1.05555556, 1.125     , 1.05084746, 1.08333333],
       [1.28187919, 1.02777778, 1.5       , 1.05084746, 1.04166667],
       [1.2885906 , 1.19444444, 1.625     , 1.10169492, 1.20833333],
       [1.29530201, 1.22222222, 1.75      , 1.15254237, 1.125     ],
       [1.30201342, 1.13888889, 1.41666667, 1.06779661, 1.08333333],
       [1.30872483, 1.22222222, 1.75      , 1.10169492, 1.04166667],
       [1.31543624, 1.08333333, 1.5       , 1.06779661, 1.04166667],
       [1.32214765, 1.27777778, 1.70833333, 1.08474576, 1.04166667],
       [1.32885906, 1.19444444, 1.54166667, 1.06779661, 1.04166667],
       [1.33557047, 1.75      , 1.5       , 1.62711864, 1.54166667],
       [1.34228188, 1.58333333, 1.5       , 1.59322034, 1.58333333],
       [1.34899329, 1.72222222, 1.45833333, 1.66101695, 1.58333333],
       [1.3557047 , 1.33333333, 1.125     , 1.50847458, 1.5       ],
       [1.36241611, 1.61111111, 1.33333333, 1.61016949, 1.58333333],
       [1.36912752, 1.38888889, 1.33333333, 1.59322034, 1.5       ],
       [1.37583893, 1.55555556, 1.54166667, 1.62711864, 1.625     ],
       [1.38255034, 1.16666667, 1.16666667, 1.38983051, 1.375     ],
       [1.38926174, 1.63888889, 1.375     , 1.61016949, 1.5       ],
       [1.39597315, 1.25      , 1.29166667, 1.49152542, 1.54166667],
       [1.40268456, 1.19444444, 1.        , 1.42372881, 1.375     ],
       [1.40939597, 1.44444444, 1.41666667, 1.54237288, 1.58333333],
       [1.41610738, 1.47222222, 1.08333333, 1.50847458, 1.375     ],
       [1.42281879, 1.5       , 1.375     , 1.62711864, 1.54166667],
       [1.4295302 , 1.36111111, 1.375     , 1.44067797, 1.5       ],
       [1.43624161, 1.66666667, 1.45833333, 1.57627119, 1.54166667],
       [1.44295302, 1.36111111, 1.41666667, 1.59322034, 1.58333333],
       [1.44966443, 1.41666667, 1.29166667, 1.52542373, 1.375     ],
       [1.45637584, 1.52777778, 1.08333333, 1.59322034, 1.58333333],
       [1.46308725, 1.36111111, 1.20833333, 1.49152542, 1.41666667],
       [1.46979866, 1.44444444, 1.5       , 1.6440678 , 1.70833333],
       [1.47651007, 1.5       , 1.33333333, 1.50847458, 1.5       ],
       [1.48322148, 1.55555556, 1.20833333, 1.66101695, 1.58333333],
       [1.48993289, 1.5       , 1.33333333, 1.62711864, 1.45833333],
       [1.4966443 , 1.58333333, 1.375     , 1.55932203, 1.5       ],
       [1.5033557 , 1.63888889, 1.41666667, 1.57627119, 1.54166667],
       [1.51006711, 1.69444444, 1.33333333, 1.6440678 , 1.54166667],
       [1.51677852, 1.66666667, 1.41666667, 1.6779661 , 1.66666667],
       [1.52348993, 1.47222222, 1.375     , 1.59322034, 1.58333333],
       [1.53020134, 1.38888889, 1.25      , 1.42372881, 1.375     ],
       [1.53691275, 1.33333333, 1.16666667, 1.47457627, 1.41666667],
       [1.54362416, 1.33333333, 1.16666667, 1.45762712, 1.375     ],
       [1.55033557, 1.41666667, 1.29166667, 1.49152542, 1.45833333],
       [1.55704698, 1.47222222, 1.29166667, 1.69491525, 1.625     ],
       [1.56375839, 1.30555556, 1.41666667, 1.59322034, 1.58333333],
       [1.5704698 , 1.47222222, 1.58333333, 1.59322034, 1.625     ],
       [1.57718121, 1.66666667, 1.45833333, 1.62711864, 1.58333333],
       [1.58389262, 1.55555556, 1.125     , 1.57627119, 1.5       ],
       [1.59060403, 1.36111111, 1.41666667, 1.52542373, 1.5       ],
       [1.59731544, 1.33333333, 1.20833333, 1.50847458, 1.5       ],
       [1.60402685, 1.33333333, 1.25      , 1.57627119, 1.45833333],
       [1.61073826, 1.5       , 1.41666667, 1.61016949, 1.54166667],
       [1.61744966, 1.41666667, 1.25      , 1.50847458, 1.45833333],
       [1.62416107, 1.19444444, 1.125     , 1.38983051, 1.375     ],
       [1.63087248, 1.36111111, 1.29166667, 1.54237288, 1.5       ],
       [1.63758389, 1.38888889, 1.41666667, 1.54237288, 1.45833333],
       [1.6442953 , 1.38888889, 1.375     , 1.54237288, 1.5       ],
       [1.65100671, 1.52777778, 1.375     , 1.55932203, 1.5       ],
       [1.65771812, 1.22222222, 1.20833333, 1.33898305, 1.41666667],
       [1.66442953, 1.38888889, 1.33333333, 1.52542373, 1.5       ],
       [1.67114094, 1.55555556, 1.54166667, 1.84745763, 2.        ],
       [1.67785235, 1.41666667, 1.29166667, 1.69491525, 1.75      ],
       [1.68456376, 1.77777778, 1.41666667, 1.83050847, 1.83333333],
       [1.69127517, 1.55555556, 1.375     , 1.77966102, 1.70833333],
       [1.69798658, 1.61111111, 1.41666667, 1.81355932, 1.875     ],
       [1.70469799, 1.91666667, 1.41666667, 1.94915254, 1.83333333],
       [1.7114094 , 1.16666667, 1.20833333, 1.59322034, 1.66666667],
       [1.71812081, 1.83333333, 1.375     , 1.89830508, 1.70833333],
       [1.72483221, 1.66666667, 1.20833333, 1.81355932, 1.70833333],
       [1.73154362, 1.80555556, 1.66666667, 1.86440678, 2.        ],
       [1.73825503, 1.61111111, 1.5       , 1.69491525, 1.79166667],
       [1.74496644, 1.58333333, 1.29166667, 1.72881356, 1.75      ],
       [1.75167785, 1.69444444, 1.41666667, 1.76271186, 1.83333333],
       [1.75838926, 1.38888889, 1.20833333, 1.6779661 , 1.79166667],
       [1.76510067, 1.41666667, 1.33333333, 1.69491525, 1.95833333],
       [1.77181208, 1.58333333, 1.5       , 1.72881356, 1.91666667],
       [1.77852349, 1.61111111, 1.41666667, 1.76271186, 1.70833333],
       [1.7852349 , 1.94444444, 1.75      , 1.96610169, 1.875     ],
       [1.79194631, 1.94444444, 1.25      , 2.        , 1.91666667],
       [1.79865772, 1.47222222, 1.08333333, 1.6779661 , 1.58333333],
       [1.80536913, 1.72222222, 1.5       , 1.79661017, 1.91666667],
       [1.81208054, 1.36111111, 1.33333333, 1.66101695, 1.79166667],
       [1.81879195, 1.94444444, 1.33333333, 1.96610169, 1.79166667],
       [1.82550336, 1.55555556, 1.29166667, 1.66101695, 1.70833333],
       [1.83221477, 1.66666667, 1.54166667, 1.79661017, 1.83333333],
       [1.83892617, 1.80555556, 1.5       , 1.84745763, 1.70833333],
       [1.84563758, 1.52777778, 1.33333333, 1.6440678 , 1.70833333],
       [1.85234899, 1.5       , 1.41666667, 1.66101695, 1.70833333],
       [1.8590604 , 1.58333333, 1.33333333, 1.77966102, 1.83333333],
       [1.86577181, 1.80555556, 1.41666667, 1.81355932, 1.625     ],
       [1.87248322, 1.86111111, 1.33333333, 1.86440678, 1.75      ],
       [1.87919463, 2.        , 1.75      , 1.91525424, 1.79166667],
       [1.88590604, 1.58333333, 1.33333333, 1.77966102, 1.875     ],
       [1.89261745, 1.55555556, 1.33333333, 1.69491525, 1.58333333],
       [1.89932886, 1.5       , 1.25      , 1.77966102, 1.54166667],
       [1.90604027, 1.94444444, 1.41666667, 1.86440678, 1.91666667],
       [1.91275168, 1.55555556, 1.58333333, 1.77966102, 1.95833333],
       [1.91946309, 1.58333333, 1.45833333, 1.76271186, 1.70833333],
       [1.9261745 , 1.47222222, 1.41666667, 1.6440678 , 1.70833333],
       [1.93288591, 1.72222222, 1.45833333, 1.74576271, 1.83333333],
       [1.93959732, 1.66666667, 1.45833333, 1.77966102, 1.95833333],
       [1.94630872, 1.72222222, 1.45833333, 1.69491525, 1.91666667],
       [1.95302013, 1.41666667, 1.29166667, 1.69491525, 1.75      ],
       [1.95973154, 1.69444444, 1.5       , 1.83050847, 1.91666667],
       [1.96644295, 1.66666667, 1.54166667, 1.79661017, 2.        ],
       [1.97315436, 1.66666667, 1.41666667, 1.71186441, 1.91666667],
       [1.97986577, 1.55555556, 1.20833333, 1.6779661 , 1.75      ],
       [1.98657718, 1.61111111, 1.41666667, 1.71186441, 1.79166667],
       [1.99328859, 1.52777778, 1.58333333, 1.74576271, 1.91666667],
       [2.        , 1.44444444, 1.41666667, 1.69491525, 1.70833333]])

###2. Standard Scaler

In [ ]:
from sklearn.preprocessing import StandardScaler
df5=df.copy(deep=True)
x5=df5.iloc[:,0:5]
scaler=StandardScaler()
x5_Scaled=scaler.fit_transform(x5)
x5_Scaled

array([[-1.72054204e+00, -9.00681170e-01,  1.03205722e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-1.69744751e+00, -1.14301691e+00, -1.24957601e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.67435299e+00, -1.38535265e+00,  3.37848329e-01,
        -1.39813811e+00, -1.31297673e+00],
       [-1.65125846e+00, -1.50652052e+00,  1.06445364e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-1.62816394e+00, -1.02184904e+00,  1.26346019e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-1.60506942e+00, -5.37177559e-01,  1.95766909e+00,
        -1.17067529e+00, -1.05003079e+00],
       [-1.58197489e+00, -1.50652052e+00,  8.00654259e-01,
        -1.34127240e+00, -1.18150376e+00],
       [-1.55888037e+00, -1.02184904e+00,  8.00654259e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-1.53578584e+00, -1.74885626e+00, -3.56360566e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.51269132e+00, -1.14301691e+00,  1.06445364e-01,
        -1.28440670e+00, -1.44444970e+00],
       [-1.48959680e+00, -5.37177559e-01,  1.49486315e+00,
        -1.28440670e+00, -1.31297673e+00],
       [-1.46650227e+00, -1.26418478e+00,  8.00654259e-01,
        -1.22754100e+00, -1.31297673e+00],
       [-1.44340775e+00, -1.26418478e+00, -1.24957601e-01,
        -1.34127240e+00, -1.44444970e+00],
       [-1.42031323e+00, -1.87002413e+00, -1.24957601e-01,
        -1.51186952e+00, -1.44444970e+00],
       [-1.39721870e+00, -5.25060772e-02,  2.18907205e+00,
        -1.45500381e+00, -1.31297673e+00],
       [-1.37412418e+00, -1.73673948e-01,  3.11468391e+00,
        -1.28440670e+00, -1.05003079e+00],
       [-1.35102965e+00, -5.37177559e-01,  1.95766909e+00,
        -1.39813811e+00, -1.05003079e+00],
       [-1.32793513e+00, -9.00681170e-01,  1.03205722e+00,
        -1.34127240e+00, -1.18150376e+00],
       [-1.30484061e+00, -1.73673948e-01,  1.72626612e+00,
        -1.17067529e+00, -1.18150376e+00],
       [-1.28174608e+00, -9.00681170e-01,  1.72626612e+00,
        -1.28440670e+00, -1.18150376e+00],
       [-1.25865156e+00, -5.37177559e-01,  8.00654259e-01,
        -1.17067529e+00, -1.31297673e+00],
       [-1.23555703e+00, -9.00681170e-01,  1.49486315e+00,
        -1.28440670e+00, -1.05003079e+00],
       [-1.21246251e+00, -1.50652052e+00,  1.26346019e+00,
        -1.56873522e+00, -1.31297673e+00],
       [-1.18936799e+00, -9.00681170e-01,  5.69251294e-01,
        -1.17067529e+00, -9.18557817e-01],
       [-1.16627346e+00, -1.26418478e+00,  8.00654259e-01,
        -1.05694388e+00, -1.31297673e+00],
       [-1.14317894e+00, -1.02184904e+00, -1.24957601e-01,
        -1.22754100e+00, -1.31297673e+00],
       [-1.12008441e+00, -1.02184904e+00,  8.00654259e-01,
        -1.22754100e+00, -1.05003079e+00],
       [-1.09698989e+00, -7.79513300e-01,  1.03205722e+00,
        -1.28440670e+00, -1.31297673e+00],
       [-1.07389537e+00, -7.79513300e-01,  8.00654259e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.05080084e+00, -1.38535265e+00,  3.37848329e-01,
        -1.22754100e+00, -1.31297673e+00],
       [-1.02770632e+00, -1.26418478e+00,  1.06445364e-01,
        -1.22754100e+00, -1.31297673e+00],
       [-1.00461179e+00, -5.37177559e-01,  8.00654259e-01,
        -1.28440670e+00, -1.05003079e+00],
       [-9.81517269e-01, -7.79513300e-01,  2.42047502e+00,
        -1.28440670e+00, -1.44444970e+00],
       [-9.58422745e-01, -4.16009689e-01,  2.65187798e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-9.35328221e-01, -1.14301691e+00,  1.06445364e-01,
        -1.28440670e+00, -1.44444970e+00],
       [-9.12233697e-01, -1.02184904e+00,  3.37848329e-01,
        -1.45500381e+00, -1.31297673e+00],
       [-8.89139173e-01, -4.16009689e-01,  1.03205722e+00,
        -1.39813811e+00, -1.31297673e+00],
       [-8.66044649e-01, -1.14301691e+00,  1.06445364e-01,
        -1.28440670e+00, -1.44444970e+00],
       [-8.42950125e-01, -1.74885626e+00, -1.24957601e-01,
        -1.39813811e+00, -1.31297673e+00],
       [-8.19855601e-01, -9.00681170e-01,  8.00654259e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-7.96761077e-01, -1.02184904e+00,  1.03205722e+00,
        -1.39813811e+00, -1.18150376e+00],
       [-7.73666553e-01, -1.62768839e+00, -1.74477836e+00,
        -1.39813811e+00, -1.18150376e+00],
       [-7.50572030e-01, -1.74885626e+00,  3.37848329e-01,
        -1.39813811e+00, -1.31297673e+00],
       [-7.27477506e-01, -1.02184904e+00,  1.03205722e+00,
        -1.22754100e+00, -7.87084847e-01],
       [-7.04382982e-01, -9.00681170e-01,  1.72626612e+00,
        -1.05694388e+00, -1.05003079e+00],
       [-6.81288458e-01, -1.26418478e+00, -1.24957601e-01,
        -1.34127240e+00, -1.18150376e+00],
       [-6.58193934e-01, -9.00681170e-01,  1.72626612e+00,
        -1.22754100e+00, -1.31297673e+00],
       [-6.35099410e-01, -1.50652052e+00,  3.37848329e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-6.12004886e-01, -6.58345429e-01,  1.49486315e+00,
        -1.28440670e+00, -1.31297673e+00],
       [-5.88910362e-01, -1.02184904e+00,  5.69251294e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-5.65815838e-01,  1.40150837e+00,  3.37848329e-01,
         5.35295827e-01,  2.64698913e-01],
       [-5.42721314e-01,  6.74501145e-01,  3.37848329e-01,
         4.21564419e-01,  3.96171883e-01],
       [-5.19626790e-01,  1.28034050e+00,  1.06445364e-01,
         6.49027235e-01,  3.96171883e-01],
       [-4.96532266e-01, -4.16009689e-01, -1.74477836e+00,
         1.37235899e-01,  1.33225943e-01],
       [-4.73437742e-01,  7.95669016e-01, -5.87763531e-01,
         4.78430123e-01,  3.96171883e-01],
       [-4.50343218e-01, -1.73673948e-01, -5.87763531e-01,
         4.21564419e-01,  1.33225943e-01],
       [-4.27248694e-01,  5.53333275e-01,  5.69251294e-01,
         5.35295827e-01,  5.27644853e-01],
       [-4.04154170e-01, -1.14301691e+00, -1.51337539e+00,
        -2.60824029e-01, -2.61192967e-01],
       [-3.81059646e-01,  9.16836886e-01, -3.56360566e-01,
         4.78430123e-01,  1.33225943e-01],
       [-3.57965122e-01, -7.79513300e-01, -8.19166497e-01,
         8.03701950e-02,  2.64698913e-01],
       [-3.34870598e-01, -1.02184904e+00, -2.43898725e+00,
        -1.47092621e-01, -2.61192967e-01],
       [-3.11776074e-01,  6.86617933e-02, -1.24957601e-01,
         2.50967307e-01,  3.96171883e-01],
       [-2.88681550e-01,  1.89829664e-01, -1.97618132e+00,
         1.37235899e-01, -2.61192967e-01],
       [-2.65587026e-01,  3.10997534e-01, -3.56360566e-01,
         5.35295827e-01,  2.64698913e-01],
       [-2.42492502e-01, -2.94841818e-01, -3.56360566e-01,
        -9.02269170e-02,  1.33225943e-01],
       [-2.19397978e-01,  1.03800476e+00,  1.06445364e-01,
         3.64698715e-01,  2.64698913e-01],
       [-1.96303454e-01, -2.94841818e-01, -1.24957601e-01,
         4.21564419e-01,  3.96171883e-01],
       [-1.73208930e-01, -5.25060772e-02, -8.19166497e-01,
         1.94101603e-01, -2.61192967e-01],
       [-1.50114406e-01,  4.32165405e-01, -1.97618132e+00,
         4.21564419e-01,  3.96171883e-01],
       [-1.27019882e-01, -2.94841818e-01, -1.28197243e+00,
         8.03701950e-02, -1.29719997e-01],
       [-1.03925358e-01,  6.86617933e-02,  3.37848329e-01,
         5.92161531e-01,  7.90590793e-01],
       [-8.08308339e-02,  3.10997534e-01, -5.87763531e-01,
         1.37235899e-01,  1.33225943e-01],
       [-5.77363100e-02,  5.53333275e-01, -1.28197243e+00,
         6.49027235e-01,  3.96171883e-01],
       [-3.46417860e-02,  3.10997534e-01, -5.87763531e-01,
         5.35295827e-01,  1.75297293e-03],
       [-1.15472620e-02,  6.74501145e-01, -3.56360566e-01,
         3.07833011e-01,  1.33225943e-01],
       [ 1.15472620e-02,  9.16836886e-01, -1.24957601e-01,
         3.64698715e-01,  2.64698913e-01],
       [ 3.46417860e-02,  1.15917263e+00, -5.87763531e-01,
         5.92161531e-01,  2.64698913e-01],
       [ 5.77363100e-02,  1.03800476e+00, -1.24957601e-01,
         7.05892939e-01,  6.59117823e-01],
       [ 8.08308339e-02,  1.89829664e-01, -3.56360566e-01,
         4.21564419e-01,  3.96171883e-01],
       [ 1.03925358e-01, -1.73673948e-01, -1.05056946e+00,
        -1.47092621e-01, -2.61192967e-01],
       [ 1.27019882e-01, -4.16009689e-01, -1.51337539e+00,
         2.35044910e-02, -1.29719997e-01],
       [ 1.50114406e-01, -4.16009689e-01, -1.51337539e+00,
        -3.33612130e-02, -2.61192967e-01],
       [ 1.73208930e-01, -5.25060772e-02, -8.19166497e-01,
         8.03701950e-02,  1.75297293e-03],
       [ 1.96303454e-01,  1.89829664e-01, -8.19166497e-01,
         7.62758643e-01,  5.27644853e-01],
       [ 2.19397978e-01, -5.37177559e-01, -1.24957601e-01,
         4.21564419e-01,  3.96171883e-01],
       [ 2.42492502e-01,  1.89829664e-01,  8.00654259e-01,
         4.21564419e-01,  5.27644853e-01],
       [ 2.65587026e-01,  1.03800476e+00,  1.06445364e-01,
         5.35295827e-01,  3.96171883e-01],
       [ 2.88681550e-01,  5.53333275e-01, -1.74477836e+00,
         3.64698715e-01,  1.33225943e-01],
       [ 3.11776074e-01, -2.94841818e-01, -1.24957601e-01,
         1.94101603e-01,  1.33225943e-01],
       [ 3.34870598e-01, -4.16009689e-01, -1.28197243e+00,
         1.37235899e-01,  1.33225943e-01],
       [ 3.57965122e-01, -4.16009689e-01, -1.05056946e+00,
         3.64698715e-01,  1.75297293e-03],
       [ 3.81059646e-01,  3.10997534e-01, -1.24957601e-01,
         4.78430123e-01,  2.64698913e-01],
       [ 4.04154170e-01, -5.25060772e-02, -1.05056946e+00,
         1.37235899e-01,  1.75297293e-03],
       [ 4.27248694e-01, -1.02184904e+00, -1.74477836e+00,
        -2.60824029e-01, -2.61192967e-01],
       [ 4.50343218e-01, -2.94841818e-01, -8.19166497e-01,
         2.50967307e-01,  1.33225943e-01],
       [ 4.73437742e-01, -1.73673948e-01, -1.24957601e-01,
         2.50967307e-01,  1.75297293e-03],
       [ 4.96532266e-01, -1.73673948e-01, -3.56360566e-01,
         2.50967307e-01,  1.33225943e-01],
       [ 5.19626790e-01,  4.32165405e-01, -3.56360566e-01,
         3.07833011e-01,  1.33225943e-01],
       [ 5.42721314e-01, -9.00681170e-01, -1.28197243e+00,
        -4.31421141e-01, -1.29719997e-01],
       [ 5.65815838e-01, -1.73673948e-01, -5.87763531e-01,
         1.94101603e-01,  1.33225943e-01],
       [ 5.88910362e-01,  5.53333275e-01,  5.69251294e-01,
         1.27454998e+00,  1.71090158e+00],
       [ 6.12004886e-01, -5.25060772e-02, -8.19166497e-01,
         7.62758643e-01,  9.22063763e-01],
       [ 6.35099410e-01,  1.52267624e+00, -1.24957601e-01,
         1.21768427e+00,  1.18500970e+00],
       [ 6.58193934e-01,  5.53333275e-01, -3.56360566e-01,
         1.04708716e+00,  7.90590793e-01],
       [ 6.81288458e-01,  7.95669016e-01, -1.24957601e-01,
         1.16081857e+00,  1.31648267e+00],
       [ 7.04382982e-01,  2.12851559e+00, -1.24957601e-01,
         1.61574420e+00,  1.18500970e+00],
       [ 7.27477506e-01, -1.14301691e+00, -1.28197243e+00,
         4.21564419e-01,  6.59117823e-01],
       [ 7.50572030e-01,  1.76501198e+00, -3.56360566e-01,
         1.44514709e+00,  7.90590793e-01],
       [ 7.73666553e-01,  1.03800476e+00, -1.28197243e+00,
         1.16081857e+00,  7.90590793e-01],
       [ 7.96761077e-01,  1.64384411e+00,  1.26346019e+00,
         1.33141568e+00,  1.71090158e+00],
       [ 8.19855601e-01,  7.95669016e-01,  3.37848329e-01,
         7.62758643e-01,  1.05353673e+00],
       [ 8.42950125e-01,  6.74501145e-01, -8.19166497e-01,
         8.76490051e-01,  9.22063763e-01],
       [ 8.66044649e-01,  1.15917263e+00, -1.24957601e-01,
         9.90221459e-01,  1.18500970e+00],
       [ 8.89139173e-01, -1.73673948e-01, -1.28197243e+00,
         7.05892939e-01,  1.05353673e+00],
       [ 9.12233697e-01, -5.25060772e-02, -5.87763531e-01,
         7.62758643e-01,  1.57942861e+00],
       [ 9.35328221e-01,  6.74501145e-01,  3.37848329e-01,
         8.76490051e-01,  1.44795564e+00],
       [ 9.58422745e-01,  7.95669016e-01, -1.24957601e-01,
         9.90221459e-01,  7.90590793e-01],
       [ 9.81517269e-01,  2.24968346e+00,  1.72626612e+00,
         1.67260991e+00,  1.31648267e+00],
       [ 1.00461179e+00,  2.24968346e+00, -1.05056946e+00,
         1.78634131e+00,  1.44795564e+00],
       [ 1.02770632e+00,  1.89829664e-01, -1.97618132e+00,
         7.05892939e-01,  3.96171883e-01],
       [ 1.05080084e+00,  1.28034050e+00,  3.37848329e-01,
         1.10395287e+00,  1.44795564e+00],
       [ 1.07389537e+00, -2.94841818e-01, -5.87763531e-01,
         6.49027235e-01,  1.05353673e+00],
       [ 1.09698989e+00,  2.24968346e+00, -5.87763531e-01,
         1.67260991e+00,  1.05353673e+00],
       [ 1.12008441e+00,  5.53333275e-01, -8.19166497e-01,
         6.49027235e-01,  7.90590793e-01],
       [ 1.14317894e+00,  1.03800476e+00,  5.69251294e-01,
         1.10395287e+00,  1.18500970e+00],
       [ 1.16627346e+00,  1.64384411e+00,  3.37848329e-01,
         1.27454998e+00,  7.90590793e-01],
       [ 1.18936799e+00,  4.32165405e-01, -5.87763531e-01,
         5.92161531e-01,  7.90590793e-01],
       [ 1.21246251e+00,  3.10997534e-01, -1.24957601e-01,
         6.49027235e-01,  7.90590793e-01],
       [ 1.23555703e+00,  6.74501145e-01, -5.87763531e-01,
         1.04708716e+00,  1.18500970e+00],
       [ 1.25865156e+00,  1.64384411e+00, -1.24957601e-01,
         1.16081857e+00,  5.27644853e-01],
       [ 1.28174608e+00,  1.88617985e+00, -5.87763531e-01,
         1.33141568e+00,  9.22063763e-01],
       [ 1.30484061e+00,  2.49201920e+00,  1.72626612e+00,
         1.50201279e+00,  1.05353673e+00],
       [ 1.32793513e+00,  6.74501145e-01, -5.87763531e-01,
         1.04708716e+00,  1.31648267e+00],
       [ 1.35102965e+00,  5.53333275e-01, -5.87763531e-01,
         7.62758643e-01,  3.96171883e-01],
       [ 1.37412418e+00,  3.10997534e-01, -1.05056946e+00,
         1.04708716e+00,  2.64698913e-01],
       [ 1.39721870e+00,  2.24968346e+00, -1.24957601e-01,
         1.33141568e+00,  1.44795564e+00],
       [ 1.42031323e+00,  5.53333275e-01,  8.00654259e-01,
         1.04708716e+00,  1.57942861e+00],
       [ 1.44340775e+00,  6.74501145e-01,  1.06445364e-01,
         9.90221459e-01,  7.90590793e-01],
       [ 1.46650227e+00,  1.89829664e-01, -1.24957601e-01,
         5.92161531e-01,  7.90590793e-01],
       [ 1.48959680e+00,  1.28034050e+00,  1.06445364e-01,
         9.33355755e-01,  1.18500970e+00],
       [ 1.51269132e+00,  1.03800476e+00,  1.06445364e-01,
         1.04708716e+00,  1.57942861e+00],
       [ 1.53578584e+00,  1.28034050e+00,  1.06445364e-01,
         7.62758643e-01,  1.44795564e+00],
       [ 1.55888037e+00, -5.25060772e-02, -8.19166497e-01,
         7.62758643e-01,  9.22063763e-01],
       [ 1.58197489e+00,  1.15917263e+00,  3.37848329e-01,
         1.21768427e+00,  1.44795564e+00],
       [ 1.60506942e+00,  1.03800476e+00,  5.69251294e-01,
         1.10395287e+00,  1.71090158e+00],
       [ 1.62816394e+00,  1.03800476e+00, -1.24957601e-01,
         8.19624347e-01,  1.44795564e+00],
       [ 1.65125846e+00,  5.53333275e-01, -1.28197243e+00,
         7.05892939e-01,  9.22063763e-01],
       [ 1.67435299e+00,  7.95669016e-01, -1.24957601e-01,
         8.19624347e-01,  1.05353673e+00],
       [ 1.69744751e+00,  4.32165405e-01,  8.00654259e-01,
         9.33355755e-01,  1.44795564e+00],
       [ 1.72054204e+00,  6.86617933e-02, -1.24957601e-01,
         7.62758643e-01,  7.90590793e-01]])

###3. Binarizer

In [ ]:
from sklearn.preprocessing import Binarizer
df6=df.copy(deep=True)
x6=df6.iloc[:,0:5]
bin=Binarizer(threshold=4)  # if the value is less than threshold value displays 0 else dispalys 1
x6_scaled=bin.fit_transform(x6)
x6_scaled

array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.]])